runmode: debug                 # 开发模式, debug, release, test

#应用配置
app:
  name: apiserver              # API Server的名字
  addr: :8888                  # HTTP绑定端口


#redis 配置
redis:
  addr: 47.97.205.190:6379
  password:
  poolsize: 10

#mongo 配置
mongo:
  addr: mongodb://47.97.205.190:27017
  username: cowboy
  password: cowboy