runmode: debug                 # 开发模式, debug, release, test
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port


app:
  name: apiserver              # API Server的名字
  addr: :8888                  # HTTP绑定端口


#redis 配置
redis:
  addr: 47.97.205.190:6379
  password:
  poolsize: 10

